import eslint from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  eslint.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        exports: 'readonly',
        global: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        // Cloudflare Workers globals
        addEventListener: 'readonly',
        URL: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        fetch: 'readonly',
        DOZO_BUCKET: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-console': 'off',
      'no-useless-escape': 'error',
      'no-empty': 'warn',
    },
    ignores: [
      '**/node_modules/**',
      '**/DistributionBuild/**',
      '**/Backup/**',
      '**/Archive/**',
      '**/Plugins/**',
      '**/wordpress/**',
      '**/*.log',
      '**/package-lock.json',
      '**/DozoCoreReport/**',
      '**/Latest Builds/**',
      '**/PublicRelease/**',
      '**/warranty-system-rs-clean/**',
      '**/ChatGPT AI/**',
      '**/Claude AI/**',
      '**/Integration/**',
      '**/Workflow/**',
      '**/Workflow DB/**',
      '**/Shared/**',
      '**/Modules/**',
      '**/Logs/**',
      '**/Reports/**',
      '**/AutoSync/**',
      '**/Diagnostics/**',
      '**/DashboardTelemetry/**',
      '**/DOZO Core/**',
      '**/Empaquetado/**',
      '**/GitSync/**',
      '**/Global/**',
      '**/Latest Updates/**',
      '**/release/**',
      '**/server/**',
      '**/updates/**',
      '**/wp-updater/**',
    ],
  },
];

